version: "3.8"
services:
  app:
    restart: always
    container_name: poke_next_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    image: jeziellopes/poke_next:latest
    networks:
      - poke_next_net

  mongo:
    restart: always
    container_name: poke_next_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - 27027:27017
    volumes:
      - poke_next_db_data:/data/db
    networks:
      - poke_next_net

volumes:
  poke_next_db_data:
    name: poke_next_db_data
  
networks:
  poke_next_net:
    name: poke_next_net