version: "3.8"
services:
  app:
    restart: always
    container_name: poke_next_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    image: jeziellopes/poke_next:latest
    networks:
      - poke_next_net

  postgres:
    image: postgres:alpine3.16
    restart: always
    container_name: poke_next_db
    environment:
      POSTGRES_DB: 'pokenext'
      POSTGRES_USER: $DB_ROOT_USER
      POSTGRES_PASSWORD: $DB_ROOT_PASSWORD
      POSTGRES_ROOT_PASSWORD: 'adminpass@root'
      PGDATA: /data/postgres
      TZ: 'UTC'
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - poke_next_db_data:/data/postgres
    networks:
      - poke_next_net

volumes:
  poke_next_db_data:
    name: poke_next_db_data
  
networks:
  poke_next_net:
    name: poke_next_net