export * from '@/presentation/components/icons/GithubIcon'
export * from '@/presentation/components/icons/PokeBallIcon'
export * from '@/presentation/components/icons/PrevIcon'
export * from '@/presentation/components/icons/NextIcon'
export * from '@/presentation/components/icons/LikeIcon'
export * from '@/presentation/components/icons/HeartIcon'
